# Generated by Django 4.2.29 on 2026-03-07 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='sprint',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['backlog_order', 'created_at']},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='parent_ticket',
        ),
        migrations.AddField(
            model_name='membership',
            name='capacity_per_sprint',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Individual capacity per sprint (in project effort_unit). Used when global_capacity is not set on the project.',
                null=True
            ),
        ),
        migrations.AddField(
            model_name='membership',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='board_type',
            field=models.CharField(default='scrum', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='code',
            field=models.CharField(
                default='PROJ',
                help_text='Prefix used for ticket IDs (e.g. PROJ -> PROJ-1, PROJ-2 ...)',
                max_length=10,
                unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='effort_unit',
            field=models.CharField(
                choices=[
                    ('story_points', 'Story Points'),
                    ('man_days', 'Man-Days'),
                    ('man_hours', 'Man-Hours')
                ],
                default='story_points',
                help_text='Unit used to estimate effort on tickets',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='global_capacity',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Global team capacity per sprint (in effort_unit). If null, capacity is managed per member.',
                null=True
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='project_icons/default.jpg', upload_to='project_icons/'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(
                choices=[
                    ('software', 'Software'),
                    ('marketing', 'Marketing'),
                    ('business', 'Business')
                ],
                default='software',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sprint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sprint',
            name='sprint_capacity',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Total team capacity for this sprint (in project effort_unit)',
                null=True
            ),
        ),
        migrations.AddField(
            model_name='ticket',
            name='attachments',
            field=models.FileField(blank=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='backlog_order',
            field=models.PositiveIntegerField(default=0, help_text='Relative priority in product backlog (lower = higher priority)'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='board_order',
            field=models.FloatField(default=0, help_text='Visual ordering on the board column'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='labels',
            field=models.CharField(blank=True, help_text="Comma-separated labels (e.g. 'frontend,auth')", max_length=255),
        ),
        migrations.AddField(
            model_name='ticket',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                help_text='Parent issue (Epic for Stories, Story for Tasks)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='subtickets',
                to='scrum.ticket'
            ),
        ),
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(
                choices=[
                    ('lowest', 'Lowest'),
                    ('low', 'Low'),
                    ('medium', 'Medium'),
                    ('high', 'High'),
                    ('highest', 'Highest')
                ],
                default='medium',
                max_length=10
            ),
        ),
        migrations.AddField(
            model_name='ticket',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='story_points',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Effort estimate (in project effort_unit)',
                null=True
            ),
        ),
        migrations.AddField(
            model_name='ticket',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='scrum.project'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(
                choices=[
                    ('admin', 'Admin'),
                    ('contributor', 'Contributor'),
                    ('read-only', 'Read-only')
                ],
                default='contributor',
                max_length=20
            ),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='sprint_duration',
            field=models.PositiveIntegerField(default=14, help_text='Default sprint duration in days (e.g. 14 = 2 weeks)'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='status',
            field=models.CharField(
                choices=[
                    ('planned', 'Planned'),
                    ('active', 'Active'),
                    ('completed', 'Completed')
                ],
                default='planned',
                max_length=20
            ),
        ),
        migrations.AlterField(
            model_name='sprintticket',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sprintticket',
            name='position',
            field=models.IntegerField(blank=True, help_text='Order in the sprint backlog (lower = higher priority)', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(
                choices=[
                    ('open', 'Open'),
                    ('todo', 'To Do'),
                    ('in_progress', 'In Progress'),
                    ('in_review', 'In Review'),
                    ('done', 'Done'),
                    ('blocked', 'Blocked')
                ],
                default='todo',
                max_length=20
            ),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(
                choices=[
                    ('task', 'Task'),
                    ('bug', 'Bug'),
                    ('user story', 'User Story'),
                    ('epic', 'Epic')
                ],
                default='user story',
                max_length=10
            ),
        ),
        migrations.AddConstraint(
            model_name='sprint',
            constraint=models.UniqueConstraint(
                condition=models.Q(('status', 'active')),
                fields=('project',),
                name='uniq_active_sprint_per_project'
            ),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='scrum.ticket'),
        ),
        migrations.AddField(
            model_name='column',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='scrum.board'),
        ),
        migrations.AddField(
            model_name='board',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='board', to='scrum.project'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='scrum.column'),
        ),
        migrations.AddConstraint(
            model_name='column',
            constraint=models.UniqueConstraint(fields=('board', 'order'), name='uniq_column_order_per_board'),
        ),
    ]