# Generated by Django 4.2.29 on 2026-03-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0002_board_column_comment_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(default='PROJ', help_text='Prefix used for ticket IDs (e.g. PROJ -> PROJ-1, PROJ-2 ...)', max_length=10, unique=True),
        ),
    ]
