# Generated by Django 5.2.7 on 2026-04-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0004_membership_team_role_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='team_role',
            field=models.CharField(choices=[('developer', 'Developer'), ('scrum_master', 'Scrum Master'), ('product_owner', 'Product Owner'), ('tester', 'Tester'), ('designer', 'Designer'), ('other', 'Other')], default='developer', max_length=20),
        ),
    ]
